### ISSUE TITLE
勝負が必ず引き分けになってしまう？？

### ISSUE THREAD

**Issue by kugimasa** [daiking1756/facial-expression-battle#40]
なかなか「**勝ち**」「**負け**」が出ない
プログラムが間違っている可能性が高いと思います
まずは調査から

**Comment by daiking1756** [comment]
targetFacialExpressionを日本語化したことによって、FaceAPIのResponseBodyに存在しないキーを取得しようとするバグが発生していた。
そのため、`localScore`も`remoteScore`も`undefined`となり、結果「引き分け」と判定されていたようだ
